################################################################################
#                 Continuous Integration Control for Travis CI                 #
#                                                                              #
# This file controls the build and test process run on Travis CI on every push #
# to the master branch. It runs the test suite and then produces a tarpaulin   #
# coverage report.                                                             #
################################################################################

language: rust
sudo: required
cache: cargo

matrix:
  include:
    
    # Linux
    - arch: arm64
      env: TARGET=aarch64-unknown-linux-gnu
    - arch: amd64
      env: TARGET=x86_64-unknown-linux-musl
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

before_cache:
  - bash ci/install_tarpaulin.sh

before_install:
  - set -e
  - rustup self update

install:
  - bash ci/install_rust.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_success:
  - bash ci/coverage.sh
